---
title: "The Accessible Possible Campsites of Macleish Field Station"
author: "Abby Moss and Elise Schatzki-McClain"
date: "April 6, 2019"
output:
  html_document:
    code_folding: hide
---

```{r, message = FALSE, warning = FALSE}

library(macleish)
library(sf)
library(leaflet)
library(tidyverse)

proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

#creates a 100ft buffer around each of the trails
tr_buffer <- macleish_layers %>%
  pluck("trails") %>%
  #convert to a projection where we can manipulate distance
  st_transform(proj4_aea) %>%
  #in meters
  st_buffer(dist = 30.48) %>%
  #convert back to a projection we can graph
  st_transform(4326)

#ccreates a 200ft buffer around each of the streams
str_buffer <- macleish_layers %>%
  pluck("streams") %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 60.96) %>%
  st_transform(4326)

#creates a 500ft buffer around each of the research buildings
res_buffer <- macleish_layers %>%
  pluck("research") %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 152.4) %>%
  st_transform(4326)

#location of previous campsite
prev_campsite <- tribble(
~point, ~lat, ~lon, 
"Current Campsite", 42.450976, -72.678154
)

#location of previous campsite
prev_campsite2 <- tribble(
  ~point, ~lat, ~lon,
  "Current Campsite", 42.458549, -72.679581
)

#center of the challenge course
challenge_course2 <- tribble(
  ~point, ~lat, ~lon, 
  "Challenge Courses", 42.451874, -72.679100
)

my_points <- tribble(
  ~point, ~lat, ~lon,
  "Parking Lot", 42.448013, -72.680663)

campsite1 <- tribble(
  ~point, ~lat, ~lon,
  "1. Possible Campsite", 42.444811, -72.679101)

campsite2 <- tribble(
  ~point, ~lat, ~lon,
  "2. Possible Campsite",42.455120, -72.685559)

leaflet() %>%
  addTiles() %>%
  addPolygons(data = macleish_layers[["buildings"]],
              weight = 1, popup = ~name) %>%
  #buffers that we want to stay within in green and avoid in red
  addPolygons(data = tr_buffer, 
               weight = 1, color = "green") %>%
  addPolygons(data = str_buffer,
              weight = 1, color = "green") %>%
  addPolygons(data = res_buffer, 
              weight = 1, color = "red", fillOpacity = 0.2) %>%
  addPolylines(data = macleish_layers[["streams"]], weight = 2) %>%
  #plots elevation lines
  addPolylines(data = pluck(macleish_layers, "contours_3m"), weight = 1) %>%
  addPolygons(data = macleish_layers[["boundary"]],
              weight = 1, fillOpacity = 0.2, color = "green") %>%
  addMarkers(data = my_points, popup = ~point) %>%
  addPolygons(data = macleish_layers[["research"]],
              weight = 1, color = "red") %>%
  #plots campsites and challenge course
  addMarkers(data = campsite1, popup = ~point) %>%
  addMarkers(data = campsite2, popup = ~point) %>%
  addMarkers(data = challenge_course2, popup = ~point) %>%
  addMarkers(data = prev_campsite, popup = ~point) %>%
  addMarkers(data = prev_campsite2, popup = ~point)


leaflet() %>%
  addTiles() %>%
  addPolygons(data = macleish_layers[["buildings"]],
              weight = 1, popup = ~name) %>%
  addPolygons(data = tr_buffer, 
               weight = 1, color = "brown") %>%
  addPolygons(data = str_buffer,
              weight = 1, color = "blue") %>%
  addPolylines(data = macleish_layers[["streams"]], weight = 2) %>%
  addPolygons(data = macleish_layers[["boundary"]],
              weight = 1, fillOpacity = 0.2, color = "green") %>%
  #plots elevation lines
  addPolylines(data = pluck(macleish_layers, "contours_3m"), weight = 1) %>%
  addMarkers(data = my_points, popup = ~point) %>%
  addPolygons(data = macleish_layers[["research"]],
              weight = 1, color = "red") %>%
  #plots campsites and challenge course
  addMarkers(data = campsite1, popup = ~point) %>%
  addMarkers(data = campsite2, popup = ~point) %>%
  addMarkers(data = challenge_course2, popup = ~point)
  

```


Analysis:

We are trying to find two possible accessible campsite locations for Macleish field station. Here, we propose two new campsites at Macleish field station that meet site requirements. Both of the sites reflect the requirements that are within 200m of a stream and 100m of a trail. They are also both 500 or more meters away from a research station or an element of a challenge course. After adding the elevation data to the graph, it became clear that the areas we are looking at are fairly flat portions of land, especially considering that the net elevation difference for the whole Macleish property is less than 1000 ft. The sites are a little further than ½ mile from the parking lot, but generally, the distances between the sites and the lot are somewhere between ½ mile and 1 mile. The one issue we did not address was having a unique forest type in the new proposed campsites. This is an aspect that would be incredibly hard to use data to determine. We could not figure out how to make sure that the forest types at these two proposed campsites would be a different forest type than at the existing campsites.

We would like Macleish staff to consider these two locations for a future campsite. They meet all the necessary requirements and they are really accessible locations. Proposed Campsite 1 is the one we feel is the better option of the two. This is because it is in a fairly remote area far from the half of the property that has research stations, buildings, and challenge courses. The other proposed campsite is also good and meets all of the requirements. This site is just in a more explored area of the property and therefore, and maybe would not be as nice or interesting to hike to. Even if it is not in the budget to make platforms for tents, maybe there could just be some area cleared so that there could be a tent set up on the ground. Since it is a relatively flat area, clearing some land to be able to set up tents and adding the location as a destination on trail maps would be enough to create a usable, nice space for Smith students. It would also be less expensive than creating a full campsite. It is hard to estimate cost, since the average cost per square foot for land clearing ranges between $1.28 and $2, but using that metric, a 25 square foot area would be between $32 and $50, and a 50 square foot are would be between $64 and $100. There would be very little environmental impact because there would be no new trails created and no construction happening on the site. However, there might be some trouble using the site during the winter or early spring due to the snow and rain that might make the site too muddy to use. This more rustic campsite could be an affordable and fun addition to the already great field station property.


Footnoes:

@Manual{R-base,
  title = {abigailmoss/sds_spacialdata_mp3},
  author = {{Abby Moss and Elise Schatzki-McClain}},
  address = {Northampton, Massachusetts},
  year = {2019},
  url = {https://github.com/abigailmoss/sds_spacialdata_mp3},
}

@Manual{R-base,
  title = {How Much Does It Cost To Clear Land Or Prepare A Construction Site?},
  author = {{Unknown}},
  organization = {HomeAdvisor},
  address = {Unknown},
  year = {2019},
  url = {https://www.homeadvisor.com/cost/landscape/clear-land-or-prepare-a-construction-site/},
}
